[build]
  command = "./build.sh"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "false"

# Next.js plugin for proper deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
