# Alternative Netlify configuration for static export
# Use this if the Next.js plugin fails

[build]
  command = "./build-static.sh"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect all routes to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
